drop policy if exists coop_respond        on supply_contract_request;
drop policy if exists buyer_insert        on supply_contract_request;
drop policy if exists coop_or_buyer_read  on supply_contract_request;
drop policy if exists tenant_write        on input_order_line;
drop policy if exists tenant_read         on input_order_line;
drop policy if exists tenant_write        on input_order;
drop policy if exists tenant_read         on input_order;
drop policy if exists tenant_read         on calibration;
drop policy if exists tenant_write        on cooperative_capacity;
drop policy if exists tenant_read         on cooperative_capacity;
drop policy if exists tenant_write        on block;
drop policy if exists tenant_read         on block;
drop policy if exists tenant_write        on plot;
drop policy if exists tenant_read         on plot;
drop policy if exists tenant_write        on member;
drop policy if exists tenant_read         on member;
drop policy if exists self_read           on app_user;
drop policy if exists coop_write          on cooperative;
drop policy if exists coop_read           on cooperative;
drop policy if exists ref_read            on weather_normals;
drop policy if exists ref_read            on weather_daily;
drop policy if exists ref_read            on region_stat;
drop policy if exists ref_read            on reference_price;
drop policy if exists ref_read            on fertiliser_rate;
drop policy if exists ref_read            on variety;
drop policy if exists ref_read            on commodity;

alter table weather_normals         disable row level security;
alter table weather_daily           disable row level security;
alter table region_stat             disable row level security;
alter table reference_price         disable row level security;
alter table fertiliser_rate         disable row level security;
alter table variety                 disable row level security;
alter table commodity               disable row level security;
alter table supply_contract_request disable row level security;
alter table input_order_line        disable row level security;
alter table input_order             disable row level security;
alter table calibration             disable row level security;
alter table cooperative_capacity    disable row level security;
alter table block                   disable row level security;
alter table plot                    disable row level security;
alter table member                  disable row level security;
alter table app_user                disable row level security;
alter table cooperative             disable row level security;

drop function if exists current_user_role();
drop function if exists current_cooperative_id();
